// 学位英语 · 词组/语句补充数据（口语表达 / 常用词缀 / 不规则动词）
// degreePhrases.ts 自动生成仅含「词组表」(category: 'phrase')；
// 本文件补齐 spoken / affix / irregular 三类，使「词组/语句」页四个分类均有真实内容。
// 数据依据《学位英语水平考试大纲》附录三(词缀)/附录四(不规则动词)/附录八(口语表达) 编制。
import type { DegreePhrase } from './degreeTypes'

// ====== 口语表达（附录八 常用口语表达用语 + 日常交际套语） ======
export const spokenPhrases: DegreePhrase[] = [
  { id: 'sp001', category: 'spoken', en: "How are you doing?", zh: '你最近怎么样？', extra: '问候', productive: true },
  { id: 'sp002', category: 'spoken', en: "It's nice to meet you.", zh: '很高兴认识你。', extra: '问候' },
  { id: 'sp003', category: 'spoken', en: 'Long time no see.', zh: '好久不见。', extra: '问候' },
  { id: 'sp004', category: 'spoken', en: "What's up?", zh: '怎么了？/ 最近忙什么？', extra: '闲聊' },
  { id: 'sp005', category: 'spoken', en: "I'm sorry to hear that.", zh: '听到这个消息我很遗憾。', extra: '同情' },
  { id: 'sp006', category: 'spoken', en: 'Congratulations!', zh: '恭喜！', extra: '祝贺' },
  { id: 'sp007', category: 'spoken', en: 'I really appreciate it.', zh: '我非常感激。', extra: '感谢' },
  { id: 'sp008', category: 'spoken', en: "You're welcome.", zh: '不客气。', extra: '感谢回应' },
  { id: 'sp009', category: 'spoken', en: 'Excuse me.', zh: '打扰一下。/ 借过。', extra: '礼貌插话', productive: true },
  { id: 'sp010', category: 'spoken', en: "I beg your pardon?", zh: '请再说一遍？', extra: '请求重复' },
  { id: 'sp011', category: 'spoken', en: 'Could you do me a favor?', zh: '能帮我个忙吗？', extra: '请求' },
  { id: 'sp012', category: 'spoken', en: "I'd love to.", zh: '我很乐意。', extra: '接受邀请', productive: true },
  { id: 'sp013', category: 'spoken', en: "That sounds great.", zh: '听起来很棒。', extra: '赞同' },
  { id: 'sp014', category: 'spoken', en: "I'm afraid I can't.", zh: '恐怕不行。', extra: '婉拒' },
  { id: 'sp015', category: 'spoken', en: 'Never mind.', zh: '没关系。/ 别在意。', extra: '安慰' },
  { id: 'sp016', category: 'spoken', en: 'Take care.', zh: '保重。', extra: '告别' },
  { id: 'sp017', category: 'spoken', en: 'See you later.', zh: '回头见。', extra: '告别' },
  { id: 'sp018', category: 'spoken', en: "What do you think?", zh: '你怎么看？', extra: '征求意见' },
  { id: 'sp019', category: 'spoken', en: 'In my opinion...', zh: '在我看来……', extra: '表达观点', productive: true },
  { id: 'sp020', category: 'spoken', en: "I'm not sure.", zh: '我不确定。', extra: '表达不确定' },
  { id: 'sp021', category: 'spoken', en: 'Could you speak more slowly?', zh: '你能说慢一点吗？', extra: '沟通' },
  { id: 'sp022', category: 'spoken', en: "I didn't catch that.", zh: '我没听清。', extra: '沟通' },
  { id: 'sp023', category: 'spoken', en: "Let's get together sometime.", zh: '我们找时间聚聚。', extra: '邀约' },
  { id: 'sp024', category: 'spoken', en: 'Have a good day!', zh: '祝你今天愉快！', extra: '祝福' }
]

// ====== 常用词缀（附录三 构词法） ======
export const affixPhrases: DegreePhrase[] = [
  { id: 'af001', category: 'affix', en: 'un-', zh: '否定（不…）', extra: 'unhappy 不高兴的', productive: true },
  { id: 'af002', category: 'affix', en: 'dis-', zh: '否定（不…）', extra: 'disagree 不同意' },
  { id: 'af003', category: 'affix', en: 'in-/im-/il-/ir-', zh: '否定（不…）', extra: 'impossible 不可能的', productive: true },
  { id: 'af004', category: 'affix', en: 'non-', zh: '非…', extra: 'nonverbal 非语言的' },
  { id: 'af005', category: 'affix', en: 're-', zh: '再，重新', extra: 'rewrite 重写', productive: true },
  { id: 'af006', category: 'affix', en: 'pre-', zh: '在…之前', extra: 'preview 预览' },
  { id: 'af007', category: 'affix', en: 'post-', zh: '在…之后', extra: 'postwar 战后的' },
  { id: 'af008', category: 'affix', en: 'mis-', zh: '错误地', extra: 'misunderstand 误解' },
  { id: 'af009', category: 'affix', en: 'over-', zh: '过度', extra: 'overwork 过度工作' },
  { id: 'af010', category: 'affix', en: 'under-', zh: '不足', extra: 'underpay 少付' },
  { id: 'af011', category: 'affix', en: 'anti-', zh: '反对', extra: 'antiwar 反战的' },
  { id: 'af012', category: 'affix', en: 'super-', zh: '超级', extra: 'supermarket 超市' },
  { id: 'af013', category: 'affix', en: 'sub-', zh: '在…下', extra: 'subway 地铁' },
  { id: 'af014', category: 'affix', en: 'inter-', zh: '之间，相互', extra: 'international 国际的', productive: true },
  { id: 'af015', category: 'affix', en: 'trans-', zh: '横穿，转移', extra: 'transport 运输' },
  { id: 'af016', category: 'affix', en: 'fore-', zh: '在前', extra: 'forecast 预报' },
  { id: 'af017', category: 'affix', en: '-er / -or', zh: '表示人（做…的人）', extra: 'teacher 老师', productive: true },
  { id: 'af018', category: 'affix', en: '-ist', zh: '表示人（…家/…者）', extra: 'scientist 科学家' },
  { id: 'af019', category: 'affix', en: '-tion / -sion', zh: '名词（动作/状态）', extra: 'education 教育', productive: true },
  { id: 'af020', category: 'affix', en: '-ment', zh: '名词（结果）', extra: 'development 发展' },
  { id: 'af021', category: 'affix', en: '-ness', zh: '名词（性质）', extra: 'happiness 幸福' },
  { id: 'af022', category: 'affix', en: '-able / -ible', zh: '形容词（能…的）', extra: 'readable 可读的', productive: true },
  { id: 'af023', category: 'affix', en: '-ful', zh: '形容词（充满…的）', extra: 'careful 小心的' },
  { id: 'af024', category: 'affix', en: '-less', zh: '形容词（无…的）', extra: 'careless 粗心的' },
  { id: 'af025', category: 'affix', en: '-ly', zh: '副词（…地）', extra: 'quickly 快速地', productive: true }
]

// ====== 不规则动词（附录四） ======
export const irregularPhrases: DegreePhrase[] = [
  { id: 'ir001', category: 'irregular', en: 'be', zh: '是', extra: 'was / were ; been' },
  { id: 'ir002', category: 'irregular', en: 'become', zh: '变成', extra: 'became ; become' },
  { id: 'ir003', category: 'irregular', en: 'begin', zh: '开始', extra: 'began ; begun' },
  { id: 'ir004', category: 'irregular', en: 'break', zh: '打破', extra: 'broke ; broken' },
  { id: 'ir005', category: 'irregular', en: 'bring', zh: '带来', extra: 'brought ; brought' },
  { id: 'ir006', category: 'irregular', en: 'build', zh: '建造', extra: 'built ; built' },
  { id: 'ir007', category: 'irregular', en: 'buy', zh: '买', extra: 'bought ; bought' },
  { id: 'ir008', category: 'irregular', en: 'catch', zh: '抓住', extra: 'caught ; caught' },
  { id: 'ir009', category: 'irregular', en: 'choose', zh: '选择', extra: 'chose ; chosen' },
  { id: 'ir010', category: 'irregular', en: 'come', zh: '来', extra: 'came ; come' },
  { id: 'ir011', category: 'irregular', en: 'do', zh: '做', extra: 'did ; done' },
  { id: 'ir012', category: 'irregular', en: 'draw', zh: '画', extra: 'drew ; drawn' },
  { id: 'ir013', category: 'irregular', en: 'drink', zh: '喝', extra: 'drank ; drunk' },
  { id: 'ir014', category: 'irregular', en: 'drive', zh: '驾驶', extra: 'drove ; driven' },
  { id: 'ir015', category: 'irregular', en: 'eat', zh: '吃', extra: 'ate ; eaten' },
  { id: 'ir016', category: 'irregular', en: 'fall', zh: '落下', extra: 'fell ; fallen' },
  { id: 'ir017', category: 'irregular', en: 'feel', zh: '感觉', extra: 'felt ; felt' },
  { id: 'ir018', category: 'irregular', en: 'find', zh: '找到', extra: 'found ; found' },
  { id: 'ir019', category: 'irregular', en: 'fly', zh: '飞', extra: 'flew ; flown' },
  { id: 'ir020', category: 'irregular', en: 'forget', zh: '忘记', extra: 'forgot ; forgotten' },
  { id: 'ir021', category: 'irregular', en: 'get', zh: '得到', extra: 'got ; got / gotten' },
  { id: 'ir022', category: 'irregular', en: 'give', zh: '给', extra: 'gave ; given' },
  { id: 'ir023', category: 'irregular', en: 'go', zh: '去', extra: 'went ; gone', productive: true },
  { id: 'ir024', category: 'irregular', en: 'grow', zh: '生长', extra: 'grew ; grown' },
  { id: 'ir025', category: 'irregular', en: 'have', zh: '有', extra: 'had ; had' },
  { id: 'ir026', category: 'irregular', en: 'hear', zh: '听见', extra: 'heard ; heard' },
  { id: 'ir027', category: 'irregular', en: 'hold', zh: '握住', extra: 'held ; held' },
  { id: 'ir028', category: 'irregular', en: 'keep', zh: '保持', extra: 'kept ; kept' },
  { id: 'ir029', category: 'irregular', en: 'know', zh: '知道', extra: 'knew ; known' },
  { id: 'ir030', category: 'irregular', en: 'leave', zh: '离开', extra: 'left ; left' },
  { id: 'ir031', category: 'irregular', en: 'make', zh: '制造', extra: 'made ; made' },
  { id: 'ir032', category: 'irregular', en: 'meet', zh: '遇见', extra: 'met ; met' },
  { id: 'ir033', category: 'irregular', en: 'read', zh: '读', extra: 'read ; read' },
  { id: 'ir034', category: 'irregular', en: 'run', zh: '跑', extra: 'ran ; run' },
  { id: 'ir035', category: 'irregular', en: 'say', zh: '说', extra: 'said ; said' },
  { id: 'ir036', category: 'irregular', en: 'see', zh: '看见', extra: 'saw ; seen' },
  { id: 'ir037', category: 'irregular', en: 'sell', zh: '卖', extra: 'sold ; sold' },
  { id: 'ir038', category: 'irregular', en: 'send', zh: '送', extra: 'sent ; sent' },
  { id: 'ir039', category: 'irregular', en: 'sing', zh: '唱', extra: 'sang ; sung' },
  { id: 'ir040', category: 'irregular', en: 'sit', zh: '坐', extra: 'sat ; sat' },
  { id: 'ir041', category: 'irregular', en: 'speak', zh: '说', extra: 'spoke ; spoken' },
  { id: 'ir042', category: 'irregular', en: 'spend', zh: '花费', extra: 'spent ; spent' },
  { id: 'ir043', category: 'irregular', en: 'stand', zh: '站立', extra: 'stood ; stood' },
  { id: 'ir044', category: 'irregular', en: 'take', zh: '拿', extra: 'took ; taken', productive: true },
  { id: 'ir045', category: 'irregular', en: 'teach', zh: '教', extra: 'taught ; taught' },
  { id: 'ir046', category: 'irregular', en: 'tell', zh: '告诉', extra: 'told ; told' },
  { id: 'ir047', category: 'irregular', en: 'think', zh: '想', extra: 'thought ; thought' },
  { id: 'ir048', category: 'irregular', en: 'understand', zh: '理解', extra: 'understood ; understood' },
  { id: 'ir049', category: 'irregular', en: 'wear', zh: '穿', extra: 'wore ; worn' },
  { id: 'ir050', category: 'irregular', en: 'write', zh: '写', extra: 'wrote ; written' }
]
